### ISSUE TITLE
Some Models won't import

### ISSUE THREAD

**Issue by DeGraphics-Studios** [powroupi/blender_mmd_tools#118]
In Blender 2.79, there are certain PMX models that won't import. Here's the Python
Traceback (most recent call last):
  File "/Users/imac/Library/Application Support/Blender/2.79/scripts/addons/io_scene_valvesource/GUI.py", line 465, in draw
    vertmap_item = item.objects[item.vs.selected_item] if is_group else context.active_object
IndexError: bpy_prop_collection[index]: index 1 out of range, size 0

location: <unknown location>:-1

Traceback (most recent call last):
  File "/Users/imac/Library/Application Support/Blender/2.79/scripts/addons/io_scene_valvesource/GUI.py", line 465, in draw
    vertmap_item = item.objects[item.vs.selected_item] if is_group else context.active_object
IndexError: bpy_prop_collection[index]: index 1 out of range, size 0

location: <unknown location>:-1

Traceback (most recent call last):
  File "/Users/imac/Library/Application Support/Blender/2.79/scripts/addons/io_scene_valvesource/GUI.py", line 465, in draw
    vertmap_item = item.objects[item.vs.selected_item] if is_group else context.active_object
IndexError: bpy_prop_collection[index]: index 1 out of range, size 0

location: <unknown location>:-1

Traceback (most recent call last):
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/operators/fileio.py", line 145, in execute
    self._do_execute(context)
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/operators/fileio.py", line 174, in _do_execute
    spa_blend_factor=self.spa_blend_factor,
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/importer.py", line 773, in execute
    self.__model = pmx.load(args['filepath'])
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/__init__.py", line 1606, in load
    model.load(fs)
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/__init__.py", line 558, in load
    num_joints = fs.readInt()
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/__init__.py", line 81, in readInt
    v, = struct.unpack('<i', self.__fin.read(4))
struct.error: unpack requires a bytes object of length 4

Traceback (most recent call last):
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/operators/fileio.py", line 145, in execute
    self._do_execute(context)
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/operators/fileio.py", line 174, in _do_execute
    spa_blend_factor=self.spa_blend_factor,
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/importer.py", line 773, in execute
    self.__model = pmx.load(args['filepath'])
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/__init__.py", line 1606, in load
    model.load(fs)
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/__init__.py", line 558, in load
    num_joints = fs.readInt()
  File "/Users/imac/Library/Application Support/Steam/steamapps/common/Blender/blender.app/Contents/Resources/2.79/scripts/addons/mmd_tools/core/pmx/__init__.py", line 81, in readInt
    v, = struct.unpack('<i', self.__fin.read(4))
struct.error: unpack requires a bytes object of length 4

**Comment by nathanvasil** [comment]
Do you have a download link for the model you're having trouble with?

**Comment by powroupi** [comment]
@DeGraphics-Studios, looks like you are using master branch (old version) of mmd_tools, try to update your mmd_tools using my [dev_test](https://github.com/powroupi/blender_mmd_tools/tree/dev_test) branch. Directly download [here](https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip). If you still get errors, please let me know. Thank you. :smile:

**Comment by powroupi** [comment]
Please open a new issue if you still can't import some models when using latest `mmd_tools` (`dev_test` branch). Thank you. :smile:
