### ISSUE TITLE
cannot import model in blender 2.8 beta Jan 13 version

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#199]
pretty sure this was working in the Jan 10 version and I deleted the old blender executable file so am badly stuck >_< if you have tips on how to fix locally pls suggest

```
Traceback (most recent call last):
  File "/Users/pthomas3/Library/Application Support/Blender/2.80/scripts/addons/mmd_tools/operators/fileio.py", line 163, in execute
    self._do_execute(context)
  File "/Users/pthomas3/Library/Application Support/Blender/2.80/scripts/addons/mmd_tools/operators/fileio.py", line 195, in _do_execute
    spa_blend_factor=self.spa_blend_factor,
  File "/Users/pthomas3/Library/Application Support/Blender/2.80/scripts/addons/mmd_tools/core/pmx/importer.py", line 785, in execute
    self.__createObjects()
  File "/Users/pthomas3/Library/Application Support/Blender/2.80/scripts/addons/mmd_tools/core/pmx/importer.py", line 74, in __createObjects
    self.__rig = mmd_model.Model.create(pmxModel.name, pmxModel.name_e, self.__scale, obj_name)
  File "/Users/pthomas3/Library/Application Support/Blender/2.80/scripts/addons/mmd_tools/core/model.py", line 69, in create
    root.mmd_type = 'ROOT'
AttributeError: 'Object' object has no attribute 'mmd_type'
```

**Comment by nagadomi** [comment]
https://github.com/powroupi/blender_mmd_tools/commit/b3468bfc10e909311469d0343f94a052ae8d50e7#r31921916

>The interface change of draw_filter in 2.8 has been reverted at 2019 01/09.
>This wrap function will cause an error.
>https://git.blender.org/gitweb/gitweb.cgi/blender.git/commitdiff/90e354fd7a6989f6d93309a2af68b8bdb60434fc

quick fix:
```patch
diff --git a/mmd_tools/panels/tool.py b/mmd_tools/panels/tool.py
index 346fe65..3da6ef4 100644
--- a/mmd_tools/panels/tool.py
+++ b/mmd_tools/panels/tool.py
@@ -22,11 +22,12 @@ if bpy.app.version < (2, 80, 0):
 
 
 def draw_filter_wrap(func):
-    if bpy.app.version < (2, 80, 0):
-        return func
-    def draw_filter_new(self_, context, layout, reverse=False):
-        func(self_, context, layout)
-    return draw_filter_new
+    return func    
+    #if bpy.app.version < (2, 80, 0):
+    #    return func
+    #def draw_filter_new(self_, context, layout, reverse=False):
+    #    func(self_, context, layout)
+    #return draw_filter_new
 
 if bpy.app.version < (2, 80, 0):
     def _layout_split(layout, factor, align):
```

**Comment by ptrthomas** [comment]
@nagadomi works like a charm ! thanks, I love this community.

**Comment by powroupi** [comment]
@nagadomi thank you for the info and the fix, I'd like to remove `draw_filter_wrap` (revert the change) if it will not be changed again, so I don't fix it rapidly. :smile:

**Comment by powroupi** [comment]
@ptrthomas I've updated `mmd_tools` (`dev_test` branch), you might test it again, thank you. :smile:

**Comment by ptrthomas** [comment]
@powroupi thank you !
