### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by yamato123212** [powroupi/blender_mmd_tools#292]
Traceback (most recent call last):
  File "D:\Blender\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "D:\Blender\2.83\scripts\addons\mmd_tools\__init__.py", line 126, in register
    properties.register()
  File "D:\Blender\2.83\scripts\addons\mmd_tools\properties\__init__.py", line 64, in register
    }
ValueError: bpy_struct "Object" registration error: mmd_root could not register

**Comment by powroupi** [comment]
Similar issue with powroupi#286.
