### ISSUE TITLE
This is not an Issue, This is a fix to one or more known issues.

### ISSUE THREAD

**Issue by HayatoTenryuu** [powroupi/blender_mmd_tools#303]
With Installation, I had the same issue as many before me. I downloaded the zip file and tried to install it. That failed.

I copied the folder to the Blender folder. That failed.

Then I tried just zipping the "mmd_tools" folder ALONE. I was able to install that zip file into Blender 2.83 and enable the add on.

I just figured you'd like to know about that solution, since you have a lot of known installation issues. I think that's the problem, is that people are installing the entire "blender_mmd_tools_dev_test.zip" file instead of extracting it, zipping "mmd_tools" folder by itself, and installing "mmd_tools.zip".

Doing this may fix #280, #282, #283, #286, and #292

<img width="1063" alt="Capture" src="https://user-images.githubusercontent.com/67559652/90296764-15a46000-de52-11ea-8da3-7a800f7e9d67.PNG">

**Comment by SwamiGattasG** [comment]
Did this. Plugin shows up but error persists when importing. On Blender 2.83

Error Console:
Traceback (most recent call last):
  File "/home/user/Blender Scripts/addons/XNALaraMesh/xps_tools.py", line 164, in execute
    status = import_xnalara_model.getInputFilename(xpsSettings)
  File "/home/user/Blender Scripts/addons/XNALaraMesh/import_xnalara_model.py", line 78, in getInputFilename
    status = xpsImport()
  File "/home/user/Blender Scripts/addons/XNALaraMesh/import_xnalara_model.py", line 156, in xpsImport
    meshes_obs = importMeshesList(armature_ob)
  File "/home/user/Blender Scripts/addons/XNALaraMesh/import_xnalara_model.py", line 475, in importMeshesList
    for meshInfo in newMeshes]
  File "/home/user/Blender Scripts/addons/XNALaraMesh/import_xnalara_model.py", line 475, in <listcomp>
    for meshInfo in newMeshes]
  File "/home/user/Blender Scripts/addons/XNALaraMesh/import_xnalara_model.py", line 577, in importMesh
    bpy.context.view_layer.objects.active = mesh_ob
RuntimeError: Error: ViewLayer 'View Layer' does not contain object '4_f003002kabe02_1_0_0'


location: <unknown location>:-1

**Comment by SwamiGattasG** [comment]
NVM it has to reside in the default scripts directory. It cannot be installed to the personal scripts folder.

**Comment by helenmar** [comment]
i have 2.9 it think .1 . I did most of your steps but left the zip file on the desktop and installed from there and that worked. Thanks for the tips <3

**Comment by Silvery2Actual** [comment]
i done did all you said.
![oh no](https://user-images.githubusercontent.com/80967649/111794905-a054ae00-88be-11eb-9f53-383a82862a02.png)
this doesn't seem right.

**Comment by ChaoticUltimateJ** [comment]
So basically, extract mmd-tools from the first zip, zip mmd-tools into a new file, then install the new file in blender?

sounds easy enough.
