### ISSUE TITLE
Blender not being able to open model

### ISSUE THREAD

**Issue by TheAlePower** [powroupi/blender_mmd_tools#356]
OS : Windows 10
Using lastest version 0.7.1

bpy.ops.mmd_tools.import_model(filepath="C:\\Users\\TheAlePower\\Desktop\\MMD\\UserFile\\Model\\Miku_Hatsune.pmd")
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\mmd_tools\operators\fileio.py", line 159, in execute
    self.__translator = DictionaryEnum.get_translator(self.dictionary)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\mmd_tools\translations.py", line 323, in get_translator
    return getTranslator(dictionary)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\mmd_tools\translations.py", line 171, in getTranslator
    elif csvfile in bpy.data.texts:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

bpy.ops.mmd_tools.import_model(filepath="C:\\Users\\TheAlePower\\Desktop\\MMD\\UserFile\\Model\\Miku_Hatsune.pmd")

**Comment by nagadomi** [comment]
See #348 . The issue is already fixed.

**Comment by TheAlePower** [comment]
how can it still happen if it's already fixed (and i'm using the latest version)?

**Comment by TheAlePower** [comment]
Resolved. Fault is on my part, i extracted the entire directory and not just mmd_tools into the addons Blender folder. For whoever has the same issue, the README.md's Usage sections contains your solution
