### ISSUE TITLE
cant enable it

### ISSUE THREAD

**Issue by a7904261024** [powroupi/blender_mmd_tools#365]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\mmd_tools\__init__.py", line 132, in register
    properties.register()
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\mmd_tools\properties\__init__.py", line 64, in register
    }
ValueError: bpy_struct "Object" registration error: mmd_root could not register

each time i try to enable it,this is what will happen

**Comment by powroupi** [comment]
See issue powroupi#253. Thank you.
