### ISSUE TITLE
PMX import fails with some models - second issue

### ISSUE THREAD

**Issue by ptrthomas** [powroupi/blender_mmd_tools#40]
Again, I haven't dug into this, but hopefully you can make sense of the error log and give me some tips:

```
Traceback (most recent call last):
  File "/Users/myuserid/Library/Application Support/Blender/2.78/scripts/addons/mmd_tools/operators/fileio.py", line 156, in execute
    spa_blend_factor=self.spa_blend_factor,
  File "/Users/myuserid/Library/Application Support/Blender/2.78/scripts/addons/mmd_tools/core/pmx/importer.py", line 749, in execute
    self.__importBones()
  File "/Users/myuserid/Library/Application Support/Blender/2.78/scripts/addons/mmd_tools/core/pmx/importer.py", line 392, in __importBones
    self.__applyIk(i, pmx_bone, pose_bones)
  File "/Users/myuserid/Library/Application Support/Blender/2.78/scripts/addons/mmd_tools/core/pmx/importer.py", line 306, in __applyIk
    c.subtarget = ik_bone.name
AttributeError: 'NoneType' object has no attribute 'name'
```

This is for this model:  http://gwenathan.deviantart.com/art/TDA-Pop-Raver-Miku-FINISHED-10-Model-DL-496738682

**Comment by powroupi** [comment]
Thank you for reporting this issue. :smile: 
I guess the IK setting of that model is incorrect or unnormal. I'll figure out the cause and try to work around it on import script. :)

**Comment by ptrthomas** [comment]
Tested and works fine now.  Thanks :)
