### ISSUE TITLE
Blender 4.0 needs your help！

### ISSUE THREAD

**Issue by Zhong5213** [powroupi/blender_mmd_tools#400]
Upon importing a model using MMD Tools in Blender, the following error is encountered:
Report: Error
Traceback (most recent call last):
  File "D:\steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\operators\fileio.py", line 163, in execute
    self._do_execute(context)
  File "D:\steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\operators\fileio.py", line 182, in _do_execute
    importer_cls().execute(
  File "D:\steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\pmx\importer.py", line 845, in execute
    self._importMaterials()
  File "D:\steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\pmx\importer.py", line 557, in __importMaterials
    texture_slot = fnMat.create_texture(self._textureTable[i.texture])
  File "D:\steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\material.py", line 420, in create_texture
    texture = self._create_texture_node('mmd_base_tex', filepath, (-4, -1))
  File "D:\steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\material.py", line 508, in _create_texture_node
    self._update_shader_nodes()
  File "D:\steam\steamapps\common\Blender\4.0\scripts\addons\mmd_tools\core\material.py", line 666, in _update_shader_nodes
    if not node_shader.outputs['Shader'].is_linked:
KeyError: 'bpy_prop_collection[key]: key "Shader" not found'

This error occurs during the material import process. It seems to be related to the absence of a "Shader" attribute in a material node.

I'm using Blender 4.0 and the latest version of MMD Tools. How can I resolve this issue?
![屏幕截图 2024-03-22 223850](https://github.com/powroupi/blender_mmd_tools/assets/91378573/0711327a-7e81-4382-84d9-9505111ccb1d)

**Comment by Zhong5213** [comment]
I am a chinese student and don't have much time to see my github everyday. If you can solve this problem, you can post the solution in my email: zhongqianjia37@gmail.com or zhongqianjia37@126.com(china mainland). What your help is of great importance to me!

**Comment by Zjuhui** [comment]
same problem, do you solve it?

**Comment by ulyssas** [comment]
Install MMD Tools 4.x from Blender Preferences. Do not create issues on this repository.

This is where you make new issues. https://github.com/MMD-Blender/blender_mmd_tools/issues

<img width="772" height="660" alt="Image" src="https://github.com/user-attachments/assets/067c4a80-07f9-40fc-90ff-4071effe6300" />
