### ISSUE TITLE
Use Blender link features in mmd model cause a lot of  error and lag.

### ISSUE THREAD

**Issue by PaulsonH** [powroupi/blender_mmd_tools#403]
I link my MMD model from file scenes to other scenes, But it keeps on showing thousands of errors in CMD  like below

I turn off the MMD tool addon, the error will disappear. 

It will show those error many times based on how many physical bone in your mmd model.

![image](https://github.com/user-attachments/assets/bd4d47d9-baf6-45ea-bc3d-3663b1debdb7)
![image](https://github.com/user-attachments/assets/a627c426-0dd1-485c-87f6-5bdbfbce342f)

Traceback (most recent call last):
AttributeError: 'Context' object has no attribute 'active_object'
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 195, in _getActiveJointObject
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 178, in _getActiveRigidbodyObject
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 193, in _getActiveJointObject
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 178, in _getActiveRigidbodyObject
Traceback (most recent call last):
    return context.active_object
    active_obj = FnContext.get_active_object(context)
Traceback (most recent call last):
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 195, in _getActiveJointObject
           ^^^^^^^^^^^^^^^^^^^^^
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 180, in _getActiveRigidbodyObject
    return context.active_object
Traceback (most recent call last):
    active_obj = FnContext.get_active_object(context)
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 220, in _getActiveMeshObject
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
WARNING:root:Object.select is deprecated since v4.0.0: Use Object.select_get() method instead
Stack (most recent call last):
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 499, in __get_select
    utils.warn_deprecation("Object.select", "v4.0.0", "Use Object.select_get() method instead")
           ^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    active_obj = FnContext.get_active_object(context)
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 222, in _getActiveMeshObject
    return context.active_object
WARNING:root:Object.select is deprecated since v4.0.0: Use Object.select_get() method instead
Stack (most recent call last):
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 499, in __get_select
    utils.warn_deprecation("Object.select", "v4.0.0", "Use Object.select_get() method instead")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 220, in _getActiveMeshObject
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
    active_obj = FnContext.get_active_object(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 222, in _getActiveMeshObject
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return context.active_object
    return context.active_object
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
    active_obj = FnContext.get_active_object(context)
WARNING:root:Object.hide is deprecated since v4.0.0: Use Object.hide_get() method instead
Stack (most recent call last):
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 509, in __get_hide
    utils.warn_deprecation("Object.hide", "v4.0.0", "Use Object.hide_get() method instead")
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 193, in _getActiveJointObject
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
    return context.active_object
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
WARNING:root:Object.hide is deprecated since v4.0.0: Use Object.hide_get() method instead
Stack (most recent call last):
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 509, in __get_hide
    utils.warn_deprecation("Object.hide", "v4.0.0", "Use Object.hide_get() method instead")
Traceback (most recent call last):
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 178, in _getActiveRigidbodyObject
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 222, in _getActiveMeshObject
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 193, in _getActiveJointObject
           ^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
    active_obj = FnContext.get_active_object(context)
Traceback (most recent call last):
AttributeError: 'Context' object has no attribute 'active_object'
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 180, in _getActiveRigidbodyObject
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 195, in _getActiveJointObject
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 220, in _getActiveMeshObject
Traceback (most recent call last):
  File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
    active_obj = FnContext.get_active_object(context)

**Comment by Jawaraisen** [comment]
Execute this from Blender 28.1 or unverified older versions

**Comment by rintrint** [comment]
Please post issues in [https://github.com/MMD-Blender/blender_mmd_tools/issues](https://github.com/MMD-Blender/blender_mmd_tools/issues).
